version: "3.5"

# https://github.com/nats-io/nats-docker/blob/main/2.10.x/alpine3.19/Dockerfile
# https://docs.nats.io/running-a-nats-service/nats_docker#creating-a-nats-cluster-with-docker-compose

# https://docs.nats.io/running-a-nats-service/configuration
# https://docs.nats.io/running-a-nats-service/introduction/flags

services:
  nats0:
    image: nats:2.10.9-alpine
    container_name: nats0
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    ports:
      - "8222:8222"
      - "4222:4222"
    volumes:
      - ./single-v2.conf:/etc/nats/nats-server.conf
      - jetstream_data_single_v2:/var/data/jetstream

volumes:
  jetstream_data_single_v2:
    name: jetstream_data_single_v2
