version: "3.5"

# https://github.com/nats-io/nats-docker/blob/main/2.10.x/alpine3.19/Dockerfile
# https://docs.nats.io/running-a-nats-service/nats_docker#creating-a-nats-cluster-with-docker-compose

# https://docs.nats.io/running-a-nats-service/configuration/clustering
# https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config

# https://github.com/bitnami/containers/blob/main/bitnami/nats/2/debian-11/Dockerfile

# https://github.com/nats-io/nats-server/issues/447#issuecomment-315598345

services:
  nats0:
    image: nats:2.10.9-alpine
    container_name: nats0
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    ports:
      - "8222:8222"
      - "4222:4222"
    volumes:
      - ./cluster.conf:/etc/nats/nats-server.conf
      - ./single-v2.conf:/etc/nats/base.conf
      - nats0_js_data:/var/data/jetstream
    environment:
      CLUSTER_ADVERTISE: "127.0.0.1:4222"
      SERVER_NAME: "nats0"

  nats1:
    image: nats:2.10.9-alpine
    container_name: nats1
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    ports:
      - "8223:8222"
      - "4223:4222"
    volumes:
      - ./cluster.conf:/etc/nats/nats-server.conf
      - ./single-v2.conf:/etc/nats/base.conf
      - nats1_js_data:/var/data/jetstream
    depends_on: [ "nats0" ]
    environment:
      CLUSTER_ADVERTISE: "127.0.0.1:4223"
      SERVER_NAME: "nats1"

  nats2:
    image: nats:2.10.9-alpine
    container_name: nats2
    command: [ "-c", "/etc/nats/nats-server.conf" ]
    ports:
      - "8224:8222"
      - "4224:4222"
    volumes:
      - ./cluster.conf:/etc/nats/nats-server.conf
      - ./single-v2.conf:/etc/nats/base.conf
      - nats2_js_data:/var/data/jetstream
    depends_on: [ "nats0" ]
    environment:
      CLUSTER_ADVERTISE: "127.0.0.1:4224"
      SERVER_NAME: "nats2"

volumes:
  nats0_js_data:
    name: nats0_js_data
  nats1_js_data:
    name: nats1_js_data
  nats2_js_data:
    name: nats2_js_data
