version: "3.4"

services:
  neo4j:
    image: neo4j:3.5.8
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/1234
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/3.5:/conf
      - neo4j_data:/data

volumes:
  neo4j_data:
    name: neo4j_data
