version: "3.4"

# https://hub.docker.com/_/nginx

services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    ports:
      - "80:80"
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      - NGINX_HOST=ksCaesar-nginx.com
      - NGINX_PORT=80
    #   - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    #   - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    #   - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

    # docker cp nginx-container:/etc/nginx/nginx.conf .
    # docker cp nginx-container:/etc/nginx/conf.d ./
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
    #   - ./templates:/etc/nginx/templates
    #   - ./conf.d:/etc/nginx/nginx.conf

