version: "3.4"

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=caesar
      - MYSQL_PASSWORD=0000
    ports:
      - "3306:3306"
