services:
  mysql:
    # image: mysql:5.7.29
    image: mysql:8.0.37
    container_name: mysql
    hostname: mysql.vHost
    restart: unless-stopped
    command:
      [
        mysqld,
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdata
      - MYSQL_USER=caesar
      - MYSQL_PASSWORD=0000
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - mysql_data:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro
      # - ./etc/5.7/my_setting.cnf:/etc/mysql/conf.d/my_setting.cnf

volumes:
  mysql_data:
    name: mysql_data
