version: '3.8'

services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo:5.0.5
    restart: on-failure
    volumes:
      - ./setup.sh:/setup.sh
      - mongo_db_setup:/data/db
      - mongo_config_setup:/data/configdb
    entrypoint:
      [ "/setup.sh" ]
      # Make sure this file exists (see below for the setup.sh)
    network_mode: "host"
    depends_on:
      - mongo0
      - mongo1
      - mongo2

  # Primary node
  mongo0:
    hostname: mongo0.dev-rs
    container_name: mongo0
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command: --replSet dev-rs --keyFile /dev-rs.key
    # network_mode: "host"
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev-rs.key:/dev-rs.key
      - mongo_db0:/data/db
      - mongo_config0:/data/configdb

  mongo1:
    hostname: mongo1.dev-rs
    container_name: mongo1
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command: --replSet dev-rs --keyFile /dev-rs.key --port 27018
    depends_on:
      - mongo0
    # network_mode: "host"
    ports:
      - 27018:27018
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev-rs.key:/dev-rs.key
      - mongo_db1:/data/db
      - mongo_config1:/data/configdb

  mongo2:
    hostname: mongo2.dev-rs
    container_name: mongo2
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command: --replSet dev-rs --keyFile /dev-rs.key --port 27019
    depends_on:
      - mongo0
    # network_mode: "host"
    ports:
      - 27019:27019
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev-rs.key:/dev-rs.key
      - mongo_db2:/data/db
      - dataConfig2:/data/configdb

volumes:
  mongo_db0:
    name: mongo_db0
  mongo_config0:
    name: mongo_config0

  mongo_db1:
    name: mongo_db1
  mongo_config1:
    name: mongo_config1

  mongo_db2:
    name: mongo_db2
  mongo_config2:
    name: mongo_config2

  mongo_db_setup:
    name: mongo_db_setup
  mongo_config_setup:
    name: mongo_config_setup

# https://hub.docker.com/_/mongo/
# https://github.com/docker-library/mongo/blob/cb8a419053858e510fc68ed2d69415b3e50011cb/4.4/Dockerfile
# https://www.fatalerrors.org/a/docker-compose-builds-mongodb-replica-set-records.html
# https://github.com/docker-library/mongo/issues/475
