# https://hub.docker.com/_/redis
# https://github.com/redis/redis/blob/7.4.1/redis.conf

services:
  redis:
    image: redis:7.4.1
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"

    # sudo sysctl -w vm.overcommit_memory="1"
    # echo 'never' | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
    sysctls:
      net.core.somaxconn: 1024

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

    environment:
      - TZ=Asia/Taipei

    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly yes"]
    volumes:
      - redis_data:/data
      - ./etc/7.4/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
    name: redis_data
