version: "3.4"

services:
  redis:
    image: redis:5.0.7
    container_name: redis
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    command: >
      bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf &&
      redis-server /usr/local/etc/redis/redis.conf --appendonly yes"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/data
      - ./etc/5.0/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  data:
    name: redis_data
